site_name: Ideias
repo_url: https://github.com/guilhermeprokisch/ideias/issues
repo_name: guilhermeprokisch/ideias
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
