site_name: Ideias
theme:
  name: material
  palette:
    primary: grey
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
