# Action to backup issues using gh2md, contributed by
# https://github.com/0ut0fcontrol.
# See https://github.com/mattduck/gh2md/issues/11.
name: Issues2Markdown
on:
  issues:
    types: [opened, edited, deleted]
  issue_comment:
    types: [created,edited, deleted]

jobs:
  to_md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Backup github issues to a markdown file.
      run: |
        pip3 install --user --upgrade setuptools
        pip3 install git+https://github.com/guilhermeprokisch/gh2md.git
        $HOME/.local/bin/gh2md $GITHUB_REPOSITORY issues --multiple-files  --idempotent
        git add .
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || git commit -am "Backup all issues"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
  to_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync Wiki
        uses: joeizzard/action-wiki-sync@master
        with:
            username: guilhermeprokisch
            access_token: ${{ secrets.GITHUB_TOKEN }}
            wiki_folder: issues
            commit_username: 'Guilherme Prokisch'
            commit_email: 'guilhermeprokisch@users.noreply.github.com'
            commit_message: 'action: wiki sync'


